// This file is auto-generated by @hey-api/openapi-ts

export type UserDto = {
    /**
     * ID пользователя
     */
    id: number;
    /**
     * Email пользователя
     */
    email: string;
    /**
     * Имя пользователя
     */
    firstName: string;
    /**
     * Фамилия пользователя
     */
    lastName: string;
    /**
     * Тип профиля
     */
    profile_type: 'employer' | 'job_seeker';
    /**
     * Аватарка пользователя
     */
    avatar_url?: string;
};

export type RegisterDto = {
    /**
     * Email пользователя
     */
    email: string;
    /**
     * Пароль пользователя
     */
    password: string;
    /**
     * Имя пользователя
     */
    firstName: string;
    /**
     * Фамилия пользователя
     */
    lastName: string;
    /**
     * Тип профиля
     */
    profile_type: 'employer' | 'job_seeker';
    /**
     * Аватарка пользователя (файл)
     */
    avatar_url?: File;
};

export type RegisterResponse = {
    /**
     * JWT access token
     */
    token: string;
    /**
     * User returned after successful registration
     */
    user: UserDto;
};

export type LoginDto = {
    /**
     * Email пользователя
     */
    email: string;
    /**
     * Пароль пользователя
     */
    password: string;
};

export type LoginResponse = {
    /**
     * JWT access token
     */
    token: string;
    /**
     * User data returned after successful registration
     */
    user: UserDto;
};

export type UserControllerGetProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/profile';
};

export type UserControllerGetProfileErrors = {
    /**
     * Пользователь не авторизован
     */
    401: unknown;
};

export type UserControllerGetProfileResponses = {
    /**
     * Получение профиля пользователя
     */
    200: UserDto;
};

export type UserControllerGetProfileResponse = UserControllerGetProfileResponses[keyof UserControllerGetProfileResponses];

export type AuthControllerRegisterData = {
    body: RegisterDto;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type AuthControllerRegisterResponses = {
    /**
     * Successful registration
     */
    201: RegisterResponse;
};

export type AuthControllerRegisterResponse = AuthControllerRegisterResponses[keyof AuthControllerRegisterResponses];

export type AuthControllerLoginData = {
    body: LoginDto;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthControllerLoginResponses = {
    /**
     * Successful login
     */
    201: LoginResponse;
};

export type AuthControllerLoginResponse = AuthControllerLoginResponses[keyof AuthControllerLoginResponses];

export type AuthControllerLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type AuthControllerLogoutResponses = {
    /**
     * Successful login
     */
    201: unknown;
};

export type ClientOptions = {
    baseURL: 'http://localhost:3002' | (string & {});
};