// This file is auto-generated by @hey-api/openapi-ts
import axios from "axios";

export * from './gen/types.gen.ts';
export * from './gen/sdk.gen.ts';


import { createClient } from '@hey-api/client-axios';

export const api = createClient({
    baseURL: 'http://localhost:3000',
    headers: {
        Authorization: `Bearer ${localStorage.getItem('token') || ''}`,
        'Content-Type': 'application/json',
    },
});

export const formDataApi = axios.create({
    baseURL: 'http://localhost:3000',
    headers: {
        Authorization: `Bearer ${localStorage.getItem('token') || ''}`,
    },
});


